### PR TITLE
8.0 - Rewrite for Webnative 0.35 & TaskPorts

### LINKED ISSUE #19: Rewrite with elm-taskport
So we can instead chain `Task`s.
https://github.com/lobanov/elm-taskport

### PR DESCRIPTION
**Pull request by icidasset**
Complete rewrite for Webnative 0.35 using https://github.com/lobanov/elm-taskport

Other changes:
- Added Typescript and an ESM build
- Nix flakes

More info the [new README 📜](https://github.com/fission-codes/webnative-elm/blob/icidasset/webnative-0.35/README.md#readme)

Closes #19

### CODE REVIEW

**Review by matheus23 — APPROVED** [review]
Yay!

Mind if we call the file system operations `read` and `write` instead of `cat` and `add`? I think that lingo may be more natural with Elm folks.

Perhaps even `listEntries` instead of `ls`, but that one I'm less sure about.

**Comment by icidasset** [comment]
@matheus23 Sounds good! There's already a `read` and `write` in there, even `readUtf8` and `writeUtf8`. I've thought about removing `cat` and `add` in Webnative itself as well, and adding `readUtf8` and `writeUtf8` there as well (seeing that you can no longer pass in strings). Should we do that in the next release?

**Comment by icidasset** [comment]
I can definitely alias `ls` to `listEntries` 👍

**Comment by matheus23** [comment]
> I've thought about removing `cat` and `add` in Webnative itself as well, and adding `readUtf8` and `writeUtf8` there as well (seeing that you can no longer pass in strings). Should we do that in the next release?

Yeah. Although what do you think about aligning it with the node.js API where this works via an optional "encoding" parameter? https://nodejs.org/api/fs.html#filehandlereadfileoptions

**Comment by icidasset** [comment]
> aligning it with the node.js API where this works via an optional "encoding" parameter

That's probably better yeah.

**Pull request merged**
